#%RAML 1.0 NamedExample
[{
  "orderid": "1",
  "categoryid": "13",
  "name": "toshiba",
  "discription": "i core 7",
  "vedio_url": "www.toshiba.com",
  "price": 7000
  }, 
  {
  "orderid": "2",
  "categoryid": "13",
  "name": "hp",
  "discription": "i core 5",
  "vedio_url": "www.toshiba.com",
  "price": 6000
 }]