#%RAML 1.0 NamedExample
 [{

             orderId: 4545,

             userId: 8787,

             name: "dell",

             date: 2021-08-05,

             amount: 8000,

             discountId: 34,

             created: "01-01-2018 06:22:12",

             status: "shipped",

             adressId: "1234"

             

            

          },

          ]