#%RAML 1.0 Overlay
extends:  craft2.raml
documentation:
  - title: Api documents
    content: this document is all about craft2
/products:
  description: get all lists of products
  get:
    responses:
      200:
        body:
          application/json:
            example:
              {
                
              }
          
        
  


