#%RAML 1.0 ResourceType
post:
  description: <<resourcePathName>> created
  responses:
    201:
      body:
        application/json:
          example: 
            <<exampleRefrence>>
              