#%RAML 1.0 NamedExample
orderpost:
  {
                "userid": 1234,
                "category": 5,
                "username": abdu,
                "orderdate": 2021-08-25,
                "status" : pending            
              }
              