#%RAML 1.0 NamedExample
{
  "orderid": 134,
         "userid": 124,
         "addressid": 202,
         "discountid": 5,
         "created": "2021-08-03",
         "modified": "2021-08-03",
         "status": "shipped",
         "amount": 550
}