#%RAML 1.0 NamedExample
users:
 [
     {
  "userid": "1",
  "username": "April",
  "discription": user account is created",
  "vedio_url": "www.toshiba.com",
  "Adress": "55 high lee way"
},
{
 "userid": "2",
  "username": "june",
  "discription": user account is created",
  "vedio_url": "www.toshiba.com",
  "Adress": "24 high lee way"
}
 ]