#%RAML 1.0 SecurityScheme
type: Basic Authentication
describedBy:
  headers:
    username:
      description: user name
    type: string
  responses:
      403:
        description: credentioal is not found,
      401:
description: password or username is incorrect        
  

      



      


    

  
  
  



    


        
  
   


  
      
    

    
    
  