#%RAML 1.0 SecurityScheme
type: OAuth 2.0
description: used token
describedBy:
  headers:
    Authorization:
    discription: 
    type: integer
  responses:
      403:
        description: credentioal is not found,
      401:
        description: token is invalid


      
    
